# generated by datamodel-codegen:
#   filename:  ai.json
#   timestamp: 2026-08-17T04:53:56+00:00

from __future__ import annotations

from pydantic import BaseModel


class Kpi(BaseModel):
    id: int
    label: str
    value: str
    period: str
    rate: str
    trend: str
    icon: str


class Series(BaseModel):
    name: str
    data: list[float]


class Statistics(BaseModel):
    categories: list[str]
    series: list[Series]


class Platform(BaseModel):
    name: str
    keys: str
    used: str
    icon: str


class TokenUsages(BaseModel):
    total: str
    limit: str
    chart_series: list[int]
    platforms: list[Platform]


class Free(BaseModel):
    value: str
    percentage: str
    label: str


class Paid(BaseModel):
    value: str
    percentage: str
    label: str


class ThisMonth(BaseModel):
    value: str
    change: str
    label: str
    trend: str


class ThisYear(BaseModel):
    value: str
    change: str
    label: str
    trend: str


class UserAnalytics(BaseModel):
    total: str
    free: Free
    paid: Paid
    this_month: ThisMonth
    this_year: ThisYear


class Today(BaseModel):
    value: str
    label: str


class Yesterday(BaseModel):
    value: str
    label: str


class ProjectsAnalytics(BaseModel):
    total: str
    today: Today
    yesterday: Yesterday
    this_month: ThisMonth
    this_year: ThisYear


class RecentTransaction(BaseModel):
    id: int
    name: str
    email: str
    package: str
    price: str
    date: str
    status: str


class AiResponse(BaseModel):
    kpis: list[Kpi]
    statistics: Statistics
    token_usages: TokenUsages
    user_analytics: UserAnalytics
    projects_analytics: ProjectsAnalytics
    recent_transactions: list[RecentTransaction]
