# generated by datamodel-codegen:
#   filename:  analytics.json
#   timestamp: 2026-08-17T04:53:50+00:00

from __future__ import annotations

from pydantic import BaseModel


class UniqueVisitors(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class TotalPageviews(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class BounceRate(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class VisitDuration(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Kpis(BaseModel):
    unique_visitors: UniqueVisitors
    total_pageviews: TotalPageviews
    bounce_rate: BounceRate
    visit_duration: VisitDuration


class VisitorAnalytics(BaseModel):
    categories: list[str]
    data: list[int]


class TopChannel(BaseModel):
    id: int
    source: str
    visitors: str


class TopPage(BaseModel):
    id: int
    source: str
    pageviews: str


class ActiveUsers(BaseModel):
    live: int
    avg_daily: str
    avg_weekly: str
    avg_monthly: str
    categories: list[str]
    series: list[int]


class Series(BaseModel):
    name: str
    data: list[int]


class AcquisitionChannels(BaseModel):
    categories: list[str]
    series: list[Series]


class SessionsByDevice(BaseModel):
    labels: list[str]
    series: list[int]


class RecentOrder(BaseModel):
    id: int
    product: str
    category: str
    country: str
    cr: str
    value: str


class AnalyticsResponse(BaseModel):
    kpis: Kpis
    visitor_analytics: VisitorAnalytics
    top_channels: list[TopChannel]
    top_pages: list[TopPage]
    active_users: ActiveUsers
    acquisition_channels: AcquisitionChannels
    sessions_by_device: SessionsByDevice
    recent_orders: list[RecentOrder]
