# generated by datamodel-codegen:
#   filename:  crm.json
#   timestamp: 2026-08-17T04:53:52+00:00

from __future__ import annotations

from pydantic import BaseModel


class ActiveDeal(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class RevenueTotal(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class ClosedDeals(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Kpis(BaseModel):
    active_deal: ActiveDeal
    revenue_total: RevenueTotal
    closed_deals: ClosedDeals


class Profit1(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Profit2(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Series(BaseModel):
    name: str
    data: list[int]


class Statistics(BaseModel):
    profit_1: Profit1
    profit_2: Profit2
    categories: list[str]
    series: list[Series]


class Marketing(BaseModel):
    value: str
    percentage: str


class Sales(BaseModel):
    value: str
    percentage: str


class EstimatedRevenue(BaseModel):
    goal_value: str
    marketing: Marketing
    sales: Sales


class Category(BaseModel):
    label: str
    percentage: str
    products: str


class SalesCategory(BaseModel):
    total: str
    categories: list[Category]
    series: list[int]


class UpcomingScheduleItem(BaseModel):
    id: int
    date: str
    time: str
    title: str
    desc: str


class RecentOrder(BaseModel):
    id: str
    customer_name: str
    customer_email: str
    product: str
    value: str
    date: str
    status: str


class CrmResponse(BaseModel):
    kpis: Kpis
    statistics: Statistics
    estimated_revenue: EstimatedRevenue
    sales_category: SalesCategory
    upcoming_schedule: list[UpcomingScheduleItem]
    recent_orders: list[RecentOrder]
