# generated by datamodel-codegen:
#   filename:  dashboard.json
#   timestamp: 2026-08-17T04:53:49+00:00

from __future__ import annotations

from pydantic import BaseModel


class Customers(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Orders(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Revenue(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Profit(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class Kpis(BaseModel):
    customers: Customers
    orders: Orders
    revenue: Revenue
    profit: Profit


class MonthlySales(BaseModel):
    categories: list[str]
    data: list[int]


class MonthlyTarget(BaseModel):
    percentage: float
    target: str
    target_trend: str
    revenue: str
    revenue_trend: str
    today: str
    today_trend: str


class Series(BaseModel):
    name: str
    data: list[float]


class Statistics(BaseModel):
    categories: list[str]
    series: list[Series]


class RecentOrder(BaseModel):
    id: int
    productName: str
    variants: str
    image: str
    category: str
    price: str
    status: str


class DashboardResponse(BaseModel):
    kpis: Kpis
    monthly_sales: MonthlySales
    monthly_target: MonthlyTarget
    statistics: Statistics
    recent_orders: list[RecentOrder]
