# generated by datamodel-codegen:
#   filename:  finance.json
#   timestamp: 2026-08-17T04:53:58+00:00

from __future__ import annotations

from pydantic import BaseModel


class Balance(BaseModel):
    balance: str
    trend: str
    change: str
    comparison: str
    account_number: str
    sparkline: list[int]


class Metric(BaseModel):
    id: int
    label: str
    value: str
    change: str
    trend: str
    comparison: str
    icon: str
    color: str


class Series(BaseModel):
    name: str
    data: list[int]


class Cashflow(BaseModel):
    revenue: str
    change: str
    categories: list[str]
    series: list[Series]


class Cards(BaseModel):
    name: str
    status: str
    number: str
    exp: str
    cvc: str


class Category(BaseModel):
    name: str
    color: str
    percentage: int


class Spending(BaseModel):
    total: str
    categories: list[Category]


class User(BaseModel):
    id: int
    avatar: str
    name: str


class Quicksend(BaseModel):
    users: list[User]


class TransactionListItem(BaseModel):
    id: int
    title: str
    subtitle: str
    amount: str
    date: str
    type: str
    icon: str


class RecentTransaction(BaseModel):
    id: int
    order_id: str
    activity: str
    price: str
    date: str
    status: str


class FinanceResponse(BaseModel):
    balance: Balance
    metrics: list[Metric]
    cashflow: Cashflow
    cards: Cards
    spending: Spending
    quicksend: Quicksend
    transaction_list: list[TransactionListItem]
    recent_transactions: list[RecentTransaction]
