# generated by datamodel-codegen:
#   filename:  logistics.json
#   timestamp: 2026-08-17T04:53:55+00:00

from __future__ import annotations

from pydantic import BaseModel


class Kpi(BaseModel):
    id: int
    label: str
    value: str
    rate: str
    trend: str
    icon: str


class Series(BaseModel):
    name: str
    data: list[int]


class DeliveryStatistics(BaseModel):
    total_deliveries: str
    categories: list[str]
    series: list[Series]


class TimelineItem(BaseModel):
    id: int
    date: str
    title: str
    time: str
    icon: str
    completed: bool


class Courier(BaseModel):
    name: str
    avatar: str


class Tracking(BaseModel):
    tracking_id: str
    status: str
    timeline: list[TimelineItem]
    courier: Courier


class RevenueEarned(BaseModel):
    total_revenue: str
    shipped_quantities: str
    series: list[Series]


class DeliveryVehicles(BaseModel):
    value: str
    change: str
    trend: str
    status: str


class Activity(BaseModel):
    id: str
    category: str
    company: str
    arrival: str
    route: str
    price: str
    status: str


class LogisticsResponse(BaseModel):
    kpis: list[Kpi]
    delivery_statistics: DeliveryStatistics
    tracking: Tracking
    revenue_earned: RevenueEarned
    delivery_vehicles: DeliveryVehicles
    activities: list[Activity]
