# generated by datamodel-codegen:
#   filename:  marketing.json
#   timestamp: 2026-08-17T04:53:51+00:00

from __future__ import annotations

from pydantic import BaseModel


class AvgClientRating(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class InstagramFollowers(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class TotalRevenue(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class Kpis(BaseModel):
    avg_client_rating: AvgClientRating
    instagram_followers: InstagramFollowers
    total_revenue: TotalRevenue


class Series(BaseModel):
    name: str
    data: list[int]


class ImpressionTraffic(BaseModel):
    total_revenue: str
    rate: str
    date_range: str
    categories: list[str]
    series: list[Series]


class NewSubscribers(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class ConversionRate(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class PageBounceRate(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class TrafficStats(BaseModel):
    new_subscribers: NewSubscribers
    conversion_rate: ConversionRate
    page_bounce_rate: PageBounceRate


class FeaturedCampaign(BaseModel):
    id: int
    creator: str
    campaign: str
    brand: str
    status: str


class TopTrafficSourceItem(BaseModel):
    id: int
    source: str
    percentage: str


class MarketingResponse(BaseModel):
    kpis: Kpis
    impression_traffic: ImpressionTraffic
    traffic_stats: TrafficStats
    featured_campaigns: list[FeaturedCampaign]
    top_traffic_source: list[TopTrafficSourceItem]
