# generated by datamodel-codegen:
#   filename:  saas.json
#   timestamp: 2026-08-17T04:53:54+00:00

from __future__ import annotations

from pydantic import BaseModel


class Revenue(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class ActiveUsers(BaseModel):
    value: str
    raw_value: int
    rate: str
    trend: str


class Clv(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class Cac(BaseModel):
    value: str
    raw_value: float
    rate: str
    trend: str


class Overview(BaseModel):
    revenue: Revenue
    active_users: ActiveUsers
    clv: Clv
    cac: Cac


class Series(BaseModel):
    name: str
    data: list[float]


class ChurnRate(BaseModel):
    value: str
    change: str
    trend: str
    series: list[Series]


class Series1(BaseModel):
    name: str
    data: list[int]


class UserGrowth(BaseModel):
    value: str
    change: str
    trend: str
    series: list[Series1]


class DigitalProduct(BaseModel):
    value: str
    trend: str


class PhysicalProduct(BaseModel):
    value: str
    trend: str


class AverageDailySales(BaseModel):
    value: str
    change: str
    trend: str


class ProductPerformance(BaseModel):
    digital_product: DigitalProduct
    physical_product: PhysicalProduct
    average_daily_sales: AverageDailySales
    categories: list[str]
    series: list[Series1]


class ConversionFunnel(BaseModel):
    categories: list[str]
    series: list[Series1]


class RecentInvoice(BaseModel):
    id: str
    date: str
    user: str
    amount: str
    status: str


class Activity(BaseModel):
    id: int
    user: str
    action: str
    invoice: str
    time: str


class SaasResponse(BaseModel):
    overview: Overview
    churn_rate: ChurnRate
    user_growth: UserGrowth
    product_performance: ProductPerformance
    conversion_funnel: ConversionFunnel
    recent_invoices: list[RecentInvoice]
    activities: list[Activity]
