# generated by datamodel-codegen:
#   filename:  sales.json
#   timestamp: 2026-08-17T04:53:57+00:00

from __future__ import annotations

from pydantic import BaseModel


class Header(BaseModel):
    title: str
    subtitle: str
    date_range: str


class Series(BaseModel):
    name: str
    data: list[int]


class Kpi(BaseModel):
    id: int
    label: str
    value: str
    rate: str
    trend: str
    comparison: str
    icon: str
    color: str
    series: list[Series]


class Statistics(BaseModel):
    categories: list[str]
    series: list[Series]


class Retention(BaseModel):
    rate: str
    change: str
    trend: str
    comparison: str
    series: list[Series]
    categories: list[str]


class Channel1(BaseModel):
    name: str
    metric: str
    total_change: str
    trend: str
    color: str


class Channel(BaseModel):
    value: str
    change: str
    trend: str
    comparison: str
    channels: list[Channel1]


class Country1(BaseModel):
    code: str
    name: str
    revenue: str
    percentage: str


class Country(BaseModel):
    countries: list[Country1]


class TopProduct(BaseModel):
    id: int
    name: str
    variants: str
    image: str
    product_id: str
    sales: int
    earnings: str
    stocks: int
    status: str


class SalesResponse(BaseModel):
    header: Header
    kpis: list[Kpi]
    statistics: Statistics
    retention: Retention
    channel: Channel
    country: Country
    top_products: list[TopProduct]
