# generated by datamodel-codegen:
#   filename:  stocks.json
#   timestamp: 2026-08-17T04:53:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class OverviewItem(BaseModel):
    symbol: str
    name: str
    logo: str
    price: str
    percentage: str
    trend: str


class Series(BaseModel):
    name: str
    data: list[float]


class PortfolioPerformance(BaseModel):
    categories: list[str]
    series: list[Series]


class Series1(BaseModel):
    name: str
    data: list[int]


class Dividend(BaseModel):
    categories: list[str]
    series: list[Series1]


class WatchlistItem(BaseModel):
    symbol: str
    name: str
    logo: str
    price: str
    percentage: str
    trend: str


class TrendingStock(BaseModel):
    symbol: str
    name: str
    logo: str
    price: str
    percentage: str
    trend: str


class LatestTransaction(BaseModel):
    id: int
    name: str
    date: str
    price: str
    category: str
    status: str
    logo: str


class StocksResponse(BaseModel):
    overview: list[OverviewItem]
    portfolio_performance: PortfolioPerformance
    dividend: Dividend
    watchlist: list[WatchlistItem]
    trending_stocks: list[TrendingStock]
    latest_transactions: list[LatestTransaction]
